{"abstract":[{"text":"Enum which describes possible error types which could happen during HTTP request\/download calls.","type":"text"}],"topicSections":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/connectionError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/otherError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/rangeError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/requestCancelled","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/requestTimedOut","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/sslError"],"anchor":"Enumeration-Cases"},{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/init(rawValue:)"]},{"anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"HttpRequestErrorType","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@E@MBXHttpRequestErrorType","modules":[{"name":"MapboxCommon"}],"title":"HttpRequestErrorType","symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"HttpRequestErrorType"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpRequestErrorType"}],"role":"symbol","roleHeading":"Enumeration"},"variants":[{"paths":["\/documentation\/mapboxcommon\/httprequesterrortype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/httprequesterrortype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/SY","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestErrorType/requestTimedOut":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/requestTimedOut","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MBXHttpRequestErrorTypeRequestTimedOut"}],"url":"\/documentation\/mapboxcommon\/httprequesterrortype\/requesttimedout","abstract":[{"type":"text","text":"Timeout error."}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestTimedOut"}],"title":"HttpRequestErrorType.requestTimedOut","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestErrorType/RawRepresentable-Implementations":{"abstract":[],"title":"RawRepresentable Implementations","url":"\/documentation\/mapboxcommon\/httprequesterrortype\/rawrepresentable-implementations","kind":"article","role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/RawRepresentable-Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestErrorType/connectionError":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/connectionError","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MBXHttpRequestErrorTypeConnectionError"}],"url":"\/documentation\/mapboxcommon\/httprequesterrortype\/connectionerror","abstract":[{"type":"text","text":"Establishing connection related error."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"connectionError"}],"title":"HttpRequestErrorType.connectionError","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestErrorType/Equatable-Implementations":{"abstract":[],"title":"Equatable Implementations","url":"\/documentation\/mapboxcommon\/httprequesterrortype\/equatable-implementations","kind":"article","role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/Equatable-Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestErrorType/init(rawValue:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/init(rawValue:)","role":"symbol","type":"topic","url":"\/documentation\/mapboxcommon\/httprequesterrortype\/init(rawvalue:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"title":"init(rawValue:)","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","abstract":[],"type":"topic","title":"MapboxMaps Documentation","role":"collection","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/SY":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/SH":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestErrorType/requestCancelled":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/requestCancelled","role":"symbol","type":"topic","navigatorTitle":[{"text":"MBXHttpRequestErrorTypeRequestCancelled","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/httprequesterrortype\/requestcancelled","abstract":[{"text":"Request was cancelled by the user.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestCancelled"}],"title":"HttpRequestErrorType.requestCancelled","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestErrorType/otherError":{"abstract":[{"type":"text","text":"Other than above error."}],"title":"HttpRequestErrorType.otherError","url":"\/documentation\/mapboxcommon\/httprequesterrortype\/othererror","kind":"symbol","navigatorTitle":[{"text":"MBXHttpRequestErrorTypeOtherError","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"otherError"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/otherError"},"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestErrorType":{"abstract":[{"text":"Enum which describes possible error types which could happen during HTTP request\/download calls.","type":"text"}],"title":"HttpRequestErrorType","url":"\/documentation\/mapboxcommon\/httprequesterrortype","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HttpRequestErrorType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"HttpRequestErrorType","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"url":"\/documentation\/mapboxcommon","title":"MapboxCommon","role":"collection","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","kind":"symbol","abstract":[]},"doc://com.mapbox.MapboxMaps/s15BitwiseCopyableP":{"title":"Swift.BitwiseCopyable","type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestErrorType/rangeError":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/rangeError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rangeError"}],"kind":"symbol","navigatorTitle":[{"text":"MBXHttpRequestErrorTypeRangeError","kind":"identifier"}],"abstract":[{"type":"text","text":"Range request failed."}],"title":"HttpRequestErrorType.rangeError","type":"topic","url":"\/documentation\/mapboxcommon\/httprequesterrortype\/rangeerror"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestErrorType/sslError":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"sslError","kind":"identifier"}],"navigatorTitle":[{"text":"MBXHttpRequestErrorTypeSSLError","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/httprequesterrortype\/sslerror","role":"symbol","abstract":[{"type":"text","text":"SSL related error."}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/sslError","title":"HttpRequestErrorType.sslError"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"MBXHttpRequestErrorType","op":"replace"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"MBXHttpRequestErrorType","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"MBXHttpRequestErrorType"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/connectionError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/otherError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/rangeError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/requestCancelled","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/requestTimedOut","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestErrorType\/sslError"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBXHttpRequestErrorType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType~1requestTimedOut\/title","value":"MBXHttpRequestErrorTypeRequestTimedOut","op":"replace"},{"value":[{"text":"MBXHttpRequestErrorTypeRequestTimedOut","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType~1requestTimedOut\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType~1connectionError\/title","value":"MBXHttpRequestErrorTypeConnectionError"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType~1connectionError\/fragments","value":[{"text":"MBXHttpRequestErrorTypeConnectionError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType~1requestCancelled\/title","value":"MBXHttpRequestErrorTypeRequestCancelled","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType~1requestCancelled\/fragments","value":[{"text":"MBXHttpRequestErrorTypeRequestCancelled","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType~1otherError\/title","value":"MBXHttpRequestErrorTypeOtherError"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType~1otherError\/fragments","value":[{"text":"MBXHttpRequestErrorTypeOtherError","kind":"identifier"}],"op":"replace"},{"value":"MBXHttpRequestErrorType","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType\/title","op":"replace"},{"op":"replace","value":[{"text":"MBXHttpRequestErrorType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType\/navigatorTitle","value":[{"kind":"identifier","text":"MBXHttpRequestErrorType"}]},{"op":"replace","value":"MBXHttpRequestErrorTypeRangeError","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType~1rangeError\/title"},{"op":"replace","value":[{"text":"MBXHttpRequestErrorTypeRangeError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType~1rangeError\/fragments"},{"value":"MBXHttpRequestErrorTypeSSLError","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType~1sslError\/title"},{"value":[{"text":"MBXHttpRequestErrorTypeSSLError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestErrorType~1sslError\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}