{"metadata":{"role":"symbol","symbolKind":"method","modules":[{"name":"MapboxCommon"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getSdkInformationByName","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXSdkInformation","text":"SdkInformation"},{"kind":"text","text":"?"}],"roleHeading":"Type Method","title":"getSdkInformationByName(forName:)","externalID":"c:objc(cs)MBXSdkInformationQuery(cm)getSdkInformationByNameForName:","navigatorTitle":[{"kind":"identifier","text":"getSdkInformationByNameForName:"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getSdkInformationByName","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forName","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"name"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"text":"SdkInformation","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXSdkInformation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformation"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]},{"parameters":[{"name":"name","content":[{"inlineContent":[{"type":"text","text":"Name of requested SDK information."},{"text":" ","type":"text"},{"type":"text","text":"For instance: “MapboxCoreMaps”, “search-sdk-android”, “mapbox-navigation-ios”, “mapbox-navigation-android”."},{"type":"text","text":" "},{"text":"You can enumerate all registered SDKs and find the name you are looking for by calling getSdkInformation.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"SdkInformation with requested name or nothing if SDK with this name is not registered"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/mapboxcommon\/sdkinformationquery\/getsdkinformationbyname(forname:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/sdkinformationquery\/getsdkinformationbyname(forname:)"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformationQuery\/getSdkInformationByName(forName:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformationQuery"]]},"sections":[],"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SdkInformationQuery":{"abstract":[{"type":"text","text":"Provides an interface to query registered Mapbox SDKs. Mapbox SDKs include Maps, Navigation, Search, and others."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformationQuery","title":"SdkInformationQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SdkInformationQuery","kind":"identifier"}],"navigatorTitle":[{"text":"SdkInformationQuery","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapboxcommon\/sdkinformationquery","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SdkInformationQuery/getSdkInformationByName(forName:)":{"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/mapboxcommon\/sdkinformationquery\/getsdkinformationbyname(forname:)","title":"getSdkInformationByName(forName:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformationQuery\/getSdkInformationByName(forName:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSdkInformationByName"},{"text":"(","kind":"text"},{"text":"forName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)MBXSdkInformation","kind":"typeIdentifier","text":"SdkInformation"},{"kind":"text","text":"?"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"getSdkInformationByNameForName:"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"url":"\/documentation\/mapboxcommon","title":"MapboxCommon","role":"collection","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","kind":"symbol","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SdkInformation":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SdkInformation"}],"type":"topic","url":"\/documentation\/mapboxcommon\/sdkinformation","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformation","title":"SdkInformation","role":"symbol","kind":"symbol","abstract":[{"text":"Provides information about a given Mapbox SDK. This information is then used to populate the “User-Agent” HTTP header","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"of HTTP requests generated from within Mapbox SDKs. Mapbox SDKs include Maps, Navigation, Search, and others."}],"navigatorTitle":[{"kind":"identifier","text":"SdkInformation"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","abstract":[],"type":"topic","title":"MapboxMaps Documentation","role":"collection","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"getSdkInformationByNameForName:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"getSdkInformationByNameForName:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformation","preciseIdentifier":"c:objc(cs)MBXSdkInformation","text":"MBXSdkInformation"},{"text":" *) ","kind":"text"},{"text":"getSdkInformationByNameForName:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"name","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Name of requested SDK information.","type":"text"},{"type":"text","text":" "},{"text":"For instance: “MapboxCoreMaps”, “search-sdk-android”, “mapbox-navigation-ios”, “mapbox-navigation-android”.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"You can enumerate all registered SDKs and find the name you are looking for by calling getSdkInformation."}]}],"name":"name"}]}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"inlineContent":[{"type":"text","text":"SdkInformation with requested name or nothing if SDK with this name is not registered"}],"type":"paragraph"}]}},{"value":"MBXSdkInformationQuery","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformationQuery\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformationQuery\/fragments","value":[{"kind":"identifier","text":"MBXSdkInformationQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformationQuery\/navigatorTitle","value":[{"text":"MBXSdkInformationQuery","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformationQuery~1getSdkInformationByName(forName:)\/title","value":"getSdkInformationByNameForName:"},{"value":[{"text":"+ ","kind":"text"},{"text":"getSdkInformationByNameForName:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformationQuery~1getSdkInformationByName(forName:)\/fragments"},{"value":"MBXSdkInformation","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformation\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBXSdkInformation"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformation\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBXSdkInformation"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformation\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}