{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"text":"setLoggingLevelForCategory:upTo:","kind":"identifier"}],"roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setLoggingLevelForCategory","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"upTo"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?)","kind":"text"}],"externalID":"c:objc(cs)MBXLogConfiguration(cm)setLoggingLevelForCategory:upTo:","role":"symbol","title":"setLoggingLevelForCategory(_:upTo:)","symbolKind":"method","modules":[{"name":"MapboxCommon"}]},"sections":[],"abstract":[{"type":"text","text":"Sets the logging level for provided category."},{"text":" ","type":"text"},{"type":"text","text":"If set, takes precedence over the default logging level."}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration"]]},"variants":[{"paths":["\/documentation\/mapboxcommon\/logconfiguration\/setlogginglevelforcategory(_:upto:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/logconfiguration\/setlogginglevelforcategory(_:upto:)"]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration\/setLoggingLevelForCategory(_:upTo:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLoggingLevelForCategory"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"category","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"upTo"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"?)"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Category that should be used for applied configuration."}]}],"name":"category"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Log messages for provided category and with lower severity than"},{"text":" ","type":"text"},{"type":"text","text":"this parameter will be filtered out. If the parameter is empty,"},{"text":" ","type":"text"},{"text":"all log messages are filtered out, i.e., logging is disabled.","type":"text"}]}],"name":"upTo"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LogConfiguration/setLoggingLevelForCategory(_:upTo:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration\/setLoggingLevelForCategory(_:upTo:)","role":"symbol","url":"\/documentation\/mapboxcommon\/logconfiguration\/setlogginglevelforcategory(_:upto:)","navigatorTitle":[{"kind":"identifier","text":"setLoggingLevelForCategory:upTo:"}],"abstract":[{"text":"Sets the logging level for provided category.","type":"text"},{"text":" ","type":"text"},{"text":"If set, takes precedence over the default logging level.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setLoggingLevelForCategory"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"upTo","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?)"}],"title":"setLoggingLevelForCategory(_:upTo:)","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","role":"collection","title":"MapboxMaps","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LogConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogConfiguration"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration","navigatorTitle":[{"text":"LogConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Class that allows to configure Mapbox SDKs logging per application."}],"url":"\/documentation\/mapboxcommon\/logconfiguration","type":"topic","kind":"symbol","role":"symbol","title":"LogConfiguration"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","abstract":[],"type":"topic","title":"MapboxMaps Documentation","role":"collection","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"url":"\/documentation\/mapboxmaps\/performance","abstract":[],"type":"topic","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","role":"collectionGroup","title":"Performance and investigations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"setLoggingLevelForCategory:upTo:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setLoggingLevelForCategory:upTo:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"setLoggingLevelForCategory:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"category","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"upTo:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"upTo"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"value":{"parameters":[{"name":"category","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Category that should be used for applied configuration."}]}]},{"name":"upTo","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Log messages for provided category and with lower severity than"},{"text":" ","type":"text"},{"type":"text","text":"this parameter will be filtered out. If the parameter is empty,"},{"text":" ","type":"text"},{"text":"all log messages are filtered out, i.e., logging is disabled.","type":"text"}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration~1setLoggingLevelForCategory(_:upTo:)\/title","op":"replace","value":"setLoggingLevelForCategory:upTo:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration~1setLoggingLevelForCategory(_:upTo:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setLoggingLevelForCategory:upTo:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration\/title","value":"MBXLogConfiguration"},{"value":[{"text":"MBXLogConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLogConfiguration"}],"op":"replace"}]}]}