{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition"]]},"variants":[{"paths":["\/documentation\/mapboxmaps\/offlineregiontilepyramiddefinition\/init(styleurl:bounds:minzoom:maxzoom:pixelratio:glyphsrasterizationmode:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxmaps\/offlineregiontilepyramiddefinition\/init(styleurl:bounds:minzoom:maxzoom:pixelratio:glyphsrasterizationmode:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition\/init(styleURL:bounds:minZoom:maxZoom:pixelRatio:glyphsRasterizationMode:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"styleURL","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"bounds","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMCoordinateBounds","text":"CoordinateBounds","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"minZoom"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxZoom"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pixelRatio"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"text":", ","kind":"text"},{"text":"glyphsRasterizationMode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMGlyphsRasterizationMode","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","text":"GlyphsRasterizationMode"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"platforms":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"styleURL","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"bounds","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMCoordinateBounds","kind":"typeIdentifier","text":"CoordinateBounds"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"minZoom"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"maxZoom","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"text":"pixelRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"glyphsRasterizationMode"},{"text":": ","kind":"text"},{"text":"GlyphsRasterizationMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBMGlyphsRasterizationMode"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithStyleURL:bounds:minZoom:maxZoom:pixelRatio:glyphsRasterizationMode:","kind":"identifier"}],"symbolKind":"init","modules":[{"name":"MapboxMaps"}],"role":"symbol","externalID":"c:objc(cs)MBMOfflineRegionTilePyramidDefinition(im)initWithStyleURL:bounds:minZoom:maxZoom:pixelRatio:glyphsRasterizationMode:","roleHeading":"Initializer","title":"init(styleURL:bounds:minZoom:maxZoom:pixelRatio:glyphsRasterizationMode:)"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"type":"topic","role":"collection","title":"MapboxMaps","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","url":"\/documentation\/mapboxmaps","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoordinateBounds":{"title":"CoordinateBounds","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CoordinateBounds","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/coordinatebounds","navigatorTitle":[{"text":"CoordinateBounds","kind":"identifier"}],"abstract":[{"type":"text","text":"A rectangular area as measured on a two-dimensional map projection."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"role":"collectionGroup","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","type":"topic","title":"Offline Support","abstract":[],"kind":"article","url":"\/documentation\/mapboxmaps\/offline"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"url":"\/documentation\/mapboxmaps\/coremaps","kind":"article","role":"collectionGroup","title":"Core Maps API","abstract":[{"type":"text","text":"Maps rendering SDK also known as GL-Native"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GlyphsRasterizationMode":{"title":"GlyphsRasterizationMode","type":"topic","url":"\/documentation\/mapboxmaps\/glyphsrasterizationmode","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode","abstract":[{"type":"text","text":"Describes glyphs rasterization modes."}],"role":"symbol","navigatorTitle":[{"text":"GlyphsRasterizationMode","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"GlyphsRasterizationMode","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","abstract":[],"type":"topic","title":"MapboxMaps Documentation","role":"collection","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionTilePyramidDefinition":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition","type":"topic","title":"OfflineRegionTilePyramidDefinition","url":"\/documentation\/mapboxmaps\/offlineregiontilepyramiddefinition","abstract":[{"text":"An offline region definition is a geographic region defined by a style URL,","type":"text"},{"type":"text","text":" "},{"text":"geographic bounding box, zoom range, and device pixel ratio. Both ","type":"text"},{"type":"codeVoice","code":"minZoom"},{"type":"text","text":" and "},{"type":"codeVoice","code":"maxZoom"},{"text":" must be ≥ 0,","type":"text"},{"type":"text","text":" "},{"text":"and ","type":"text"},{"type":"codeVoice","code":"maxZoom"},{"text":" must be ≥ ","type":"text"},{"type":"codeVoice","code":"minZoom"},{"text":". The ","type":"text"},{"code":"maxZoom","type":"codeVoice"},{"text":" may be ∞, in which case for each tile source,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the region will include tiles from "},{"code":"minZoom","type":"codeVoice"},{"type":"text","text":" up to the maximum zoom level provided by that source."},{"type":"text","text":" "},{"text":"The ","type":"text"},{"type":"codeVoice","code":"pixelRatio"},{"type":"text","text":" must be ≥ 0 and should typically be 1.0 or 2.0."}],"navigatorTitle":[{"text":"OfflineRegionTilePyramidDefinition","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OfflineRegionTilePyramidDefinition"}],"kind":"symbol","deprecated":true,"role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionTilePyramidDefinition/init(styleURL:bounds:minZoom:maxZoom:pixelRatio:glyphsRasterizationMode:)":{"type":"topic","url":"\/documentation\/mapboxmaps\/offlineregiontilepyramiddefinition\/init(styleurl:bounds:minzoom:maxzoom:pixelratio:glyphsrasterizationmode:)","navigatorTitle":[{"text":"initWithStyleURL:bounds:minZoom:maxZoom:pixelRatio:glyphsRasterizationMode:","kind":"identifier"}],"kind":"symbol","title":"init(styleURL:bounds:minZoom:maxZoom:pixelRatio:glyphsRasterizationMode:)","deprecated":true,"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"styleURL","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"bounds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CoordinateBounds","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCoordinateBounds"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minZoom"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"maxZoom","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pixelRatio"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"glyphsRasterizationMode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MBMGlyphsRasterizationMode","text":"GlyphsRasterizationMode","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionTilePyramidDefinition\/init(styleURL:bounds:minZoom:maxZoom:pixelRatio:glyphsRasterizationMode:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithStyleURL:bounds:minZoom:maxZoom:pixelRatio:glyphsRasterizationMode:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithStyleURL:bounds:minZoom:maxZoom:pixelRatio:glyphsRasterizationMode:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithStyleURL:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"styleURL","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"bounds:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)MBMCoordinateBounds","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoordinateBounds","text":"MBMCoordinateBounds"},{"text":" *) ","kind":"text"},{"text":"bounds","kind":"internalParam"},{"kind":"text","text":" "},{"text":"minZoom:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"minZoom","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"maxZoom:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"maxZoom"},{"kind":"text","text":" "},{"text":"pixelRatio:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:f","kind":"typeIdentifier","text":"float"},{"kind":"text","text":") "},{"text":"pixelRatio","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"glyphsRasterizationMode:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBMGlyphsRasterizationMode","kind":"typeIdentifier","text":"MBMGlyphsRasterizationMode","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GlyphsRasterizationMode"},{"kind":"text","text":") "},{"text":"glyphsRasterizationMode","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/title","op":"replace","value":"MBMCoordinateBounds"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/fragments","value":[{"kind":"identifier","text":"MBMCoordinateBounds"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CoordinateBounds\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCoordinateBounds"}]},{"value":"MBMGlyphsRasterizationMode","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/title","op":"replace"},{"op":"replace","value":[{"text":"MBMGlyphsRasterizationMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1GlyphsRasterizationMode\/navigatorTitle","value":[{"text":"MBMGlyphsRasterizationMode","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MBMOfflineRegionTilePyramidDefinition","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition\/fragments","value":[{"text":"MBMOfflineRegionTilePyramidDefinition","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition\/navigatorTitle","value":[{"kind":"identifier","text":"MBMOfflineRegionTilePyramidDefinition"}],"op":"replace"},{"value":"initWithStyleURL:bounds:minZoom:maxZoom:pixelRatio:glyphsRasterizationMode:","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition~1init(styleURL:bounds:minZoom:maxZoom:pixelRatio:glyphsRasterizationMode:)\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionTilePyramidDefinition~1init(styleURL:bounds:minZoom:maxZoom:pixelRatio:glyphsRasterizationMode:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithStyleURL:bounds:minZoom:maxZoom:pixelRatio:glyphsRasterizationMode:"}]}]}]}