{"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"Result of HTTP request call."}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse\/result","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/mapboxcommon\/httpresponse\/result"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"result","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier","text":"Result"},{"text":"<","kind":"text"},{"text":"HttpResponseData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXHttpResponseData","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponseData"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXHttpRequestError","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError","text":"HttpRequestError","kind":"typeIdentifier"},{"text":"> { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"metadata":{"roleHeading":"Instance Property","extendedModule":"MapboxCommon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"result"},{"text":": ","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXHttpResponseData","text":"HttpResponseData"},{"text":", ","kind":"text"},{"text":"HttpRequestError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXHttpRequestError"},{"kind":"text","text":">"}],"externalID":"s:So15MBXHttpResponseC12MapboxCommonE6results6ResultOySo0aB4DataCSo0A12RequestErrorCGvp","role":"symbol","title":"result","symbolKind":"property","modules":[{"name":"MapboxCommon"}]},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"url":"\/documentation\/mapboxcommon","title":"MapboxCommon","role":"collection","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","kind":"symbol","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","abstract":[],"type":"topic","title":"MapboxMaps Documentation","role":"collection","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpResponse":{"kind":"symbol","abstract":[{"type":"text","text":"Record which is used to report HTTP response to the caller."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse","title":"HttpResponse","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HttpResponse"}],"type":"topic","navigatorTitle":[{"text":"HttpResponse","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapboxcommon\/httpresponse"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpResponseData":{"title":"HttpResponseData","type":"topic","kind":"symbol","abstract":[{"text":"Record which contains data received in HTTP response.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpResponseData","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"HttpResponseData","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponseData","url":"\/documentation\/mapboxcommon\/httpresponsedata"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpResponse/result":{"kind":"symbol","title":"result","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"result"},{"text":": ","kind":"text"},{"text":"Result","preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"HttpResponseData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBXHttpResponseData"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBXHttpRequestError","kind":"typeIdentifier","text":"HttpRequestError"},{"kind":"text","text":">"}],"url":"\/documentation\/mapboxcommon\/httpresponse\/result","abstract":[{"text":"Result of HTTP request call.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpResponse\/result","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequestError":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequestError","abstract":[{"type":"text","text":"Record which contains detailed information about HTTP error happened during request\/download call."}],"role":"symbol","navigatorTitle":[{"text":"HttpRequestError","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"HttpRequestError","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/httprequesterror","kind":"symbol","title":"HttpRequestError","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/title","value":"MBXHttpResponse"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/fragments","value":[{"text":"MBXHttpResponse","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponse\/navigatorTitle","value":[{"text":"MBXHttpResponse","kind":"identifier"}],"op":"replace"},{"value":"MBXHttpResponseData","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponseData\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponseData\/fragments","op":"replace","value":[{"text":"MBXHttpResponseData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpResponseData\/navigatorTitle","value":[{"kind":"identifier","text":"MBXHttpResponseData"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestError\/title","value":"MBXHttpRequestError","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestError\/fragments","value":[{"kind":"identifier","text":"MBXHttpRequestError"}],"op":"replace"},{"value":[{"text":"MBXHttpRequestError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequestError\/navigatorTitle"}]}]}