{"metadata":{"modules":[{"name":"MapboxCommon"}],"symbolKind":"init","title":"init(point:)","externalID":"c:objc(cs)MBXGeometry(im)initWithPoint:","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"point"},{"text":": ","kind":"text"},{"text":"NSValue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSValue"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithPoint:"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/init(point:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"point","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"location"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSValue","text":"NSValue","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapboxcommon\/geometry\/init(point:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/geometry\/init(point:)"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","abstract":[],"type":"topic","title":"MapboxMaps Documentation","role":"collection","kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"url":"\/documentation\/mapboxcommon","title":"MapboxCommon","role":"collection","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","kind":"symbol","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry":{"navigatorTitle":[{"kind":"identifier","text":"Geometry"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry","kind":"symbol","title":"Geometry","role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/mapboxcommon\/geometry","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Geometry","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/Geometry/init(point:)":{"title":"init(point:)","url":"\/documentation\/mapboxcommon\/geometry\/init(point:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"point","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSValue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSValue"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithPoint:"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/Geometry\/init(point:)","type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithPoint:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithPoint:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithPoint:"},{"text":"(","kind":"text"},{"text":"NSValue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSValue"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"location"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/title","value":"MBXGeometry"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/fragments","value":[{"text":"MBXGeometry","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry\/navigatorTitle","value":[{"text":"MBXGeometry","kind":"identifier"}],"op":"replace"},{"value":"initWithPoint:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1init(point:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPoint:"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1Geometry~1init(point:)\/fragments"}]}]}